/**
 * Zena Avatar Types
 * TypeScript definitions for avatar communication
 */

// Viseme data from Rhubarb or other lip sync tools
export interface VisemeCue {
    start: number;
    end: number;
    value: 'X' | 'A' | 'B' | 'C' | 'D' | 'E' | 'F' | 'G' | 'H';
}

// Animation beat from LLM
export interface AnimationBeat {
    t: number; // Timestamp in seconds
    action:
    | 'browRaise'
    | 'browFurrow'
    | 'smile'
    | 'frown'
    | 'eyeWiden'
    | 'eyeNarrow'
    | 'headTilt'
    | 'headNod'
    | 'blink';
    amount: number; // -1 to 1
}

// Full animation plan (can be generated by LLM)
export interface AnimationPlan {
    emotion:
    | 'neutral'
    | 'confident'
    | 'serious'
    | 'happy'
    | 'concerned'
    | 'thinking'
    | 'surprised'
    | 'focused'
    | 'amused'
    | 'empathetic';
    intensity: number; // 0 to 1
    beats?: AnimationBeat[];
    visemes?: VisemeCue[];
}

// Avatar states
export type AvatarState = 'idle' | 'listening' | 'thinking' | 'speaking';

// Messages TO Godot
export type GodotMessage =
    | { type: 'SET_STATE'; state: AvatarState; expression?: string; intensity?: number; visemes?: VisemeCue[] }
    | { type: 'SET_EXPRESSION'; expression: string; intensity: number }
    | { type: 'PLAY_VISEMES'; visemes: VisemeCue[] }
    | { type: 'PLAY_ANIMATION_PLAN'; emotion: string; intensity: number; beats?: AnimationBeat[]; visemes?: VisemeCue[] }
    | { type: 'TRIGGER_BLINK' }
    | { type: 'LOOK_AT'; x: number; y: number }
    | { type: 'SET_AMPLITUDE'; amplitude: number };

// Messages FROM Godot
export type GodotEvent =
    | { type: 'GODOT_READY' }
    | { type: 'AVATAR_READY' }
    | { type: 'STATE_CHANGED'; oldState: AvatarState; newState: AvatarState }
    | { type: 'SPEAKING_FINISHED' }
    | { type: 'VISEMES_FINISHED' };

// Hook options
export interface UseGodotBridgeOptions {
    onReady?: () => void;
    onStateChange?: (oldState: AvatarState, newState: AvatarState) => void;
    onSpeakingFinished?: () => void;
}

// Viseme data file format
export interface VisemeDataFile {
    duration: number;
    visemes: VisemeCue[];
}
