
export const MOCK_FOCUS_THREADS = [
    {
        id: 'mock-focus-1',
        subject: 'Urgent: Contract Review for 123 Main St',
        participants: ['john.doe@example.com', 'jane.smith@lawfirm.com'],
        classification: 'inquiry',
        category: 'focus',
        riskLevel: 'high',
        riskReason: 'Time sensitive contract review',
        nextAction: 'Review contract',
        nextActionOwner: 'agent',
        lastMessageAt: new Date(Date.now() - 1000 * 60 * 30), // 30 mins ago
        lastReplyAt: null,
        summary: 'Client needs urgent review of the contract terms before signing.',
        draftResponse: 'Hi John, I will review this immediately and get back to you by EOD.',
        propertyId: 'prop-123',
        dealId: 'deal-123',
        stage: 'negotiation',
        createdAt: new Date(),
        updatedAt: new Date(),
        property: {
            id: 'prop-123',
            address: '123 Main St, Springfield',
        },
        deal: {
            id: 'deal-123',
            stage: 'negotiation',
            riskLevel: 'high',
        },
    },
    {
        id: 'mock-focus-2',
        subject: 'Viewing Request: 456 Elm St',
        participants: ['potential.buyer@gmail.com'],
        classification: 'viewing_request',
        category: 'focus',
        riskLevel: 'medium',
        riskReason: null,
        nextAction: 'Schedule viewing',
        nextActionOwner: 'agent',
        lastMessageAt: new Date(Date.now() - 1000 * 60 * 60 * 2), // 2 hours ago
        lastReplyAt: null,
        summary: 'Buyer wants to see the property this weekend.',
        draftResponse: null,
        propertyId: 'prop-456',
        dealId: null,
        stage: 'lead',
        createdAt: new Date(),
        updatedAt: new Date(),
        property: {
            id: 'prop-456',
            address: '456 Elm St, Shelbyville',
        },
        deal: null,
    },
    {
        id: 'mock-focus-3',
        subject: 'Offer received for 789 Oak Ave',
        participants: ['agent.smith@realty.com'],
        classification: 'offer',
        category: 'focus',
        riskLevel: 'high',
        riskReason: 'New offer needs presentation',
        nextAction: 'Present offer',
        nextActionOwner: 'agent',
        lastMessageAt: new Date(Date.now() - 1000 * 60 * 60 * 5), // 5 hours ago
        lastReplyAt: null,
        summary: 'Received an offer of $850k. Needs to be presented to vendor.',
        draftResponse: null,
        propertyId: 'prop-789',
        dealId: 'deal-789',
        stage: 'offer',
        createdAt: new Date(),
        updatedAt: new Date(),
        property: {
            id: 'prop-789',
            address: '789 Oak Ave, Capital City',
        },
        deal: {
            id: 'deal-789',
            stage: 'offer',
            riskLevel: 'medium',
        },
    },
    {
        id: 'mock-focus-4',
        subject: 'Question about school zones',
        participants: ['parent@school.org'],
        classification: 'inquiry',
        category: 'focus',
        riskLevel: 'low',
        riskReason: null,
        nextAction: 'Reply to inquiry',
        nextActionOwner: 'agent',
        lastMessageAt: new Date(Date.now() - 1000 * 60 * 60 * 24), // 1 day ago
        lastReplyAt: null,
        summary: 'Asking if 123 Main St is in the good school zone.',
        draftResponse: null,
        propertyId: 'prop-123',
        dealId: null,
        stage: 'lead',
        createdAt: new Date(),
        updatedAt: new Date(),
        property: {
            id: 'prop-123',
            address: '123 Main St, Springfield',
        },
        deal: null,
    },
    {
        id: 'mock-focus-5',
        subject: 'Maintenance issue at rental',
        participants: ['tenant@rental.com'],
        classification: 'maintenance',
        category: 'focus',
        riskLevel: 'medium',
        riskReason: 'Leak reported',
        nextAction: 'Coordinate repair',
        nextActionOwner: 'agent',
        lastMessageAt: new Date(Date.now() - 1000 * 60 * 60 * 26), // 1 day 2 hours ago
        lastReplyAt: null,
        summary: 'Tenant reports a leaking tap in the bathroom.',
        draftResponse: null,
        propertyId: 'prop-000',
        dealId: null,
        stage: null,
        createdAt: new Date(),
        updatedAt: new Date(),
        property: {
            id: 'prop-000',
            address: '10 Rental Way',
        },
        deal: null,
    },
];

export const MOCK_WAITING_THREADS = [
    {
        id: 'mock-waiting-1',
        subject: 'Re: Contract sent',
        participants: ['lawyer@firm.com'],
        classification: 'legal',
        category: 'waiting',
        riskLevel: 'medium',
        riskReason: null,
        nextAction: 'Wait for review',
        nextActionOwner: 'external',
        lastMessageAt: new Date(Date.now() - 1000 * 60 * 60 * 48), // 2 days ago
        lastReplyAt: new Date(Date.now() - 1000 * 60 * 60 * 49),
        summary: 'Awaiting lawyer review of the contract.',
        draftResponse: null,
        propertyId: 'prop-111',
        dealId: 'deal-111',
        stage: 'contract',
        createdAt: new Date(),
        updatedAt: new Date(),
        property: {
            id: 'prop-111',
            address: '111 First St',
        },
        deal: {
            id: 'deal-111',
            stage: 'contract',
            riskLevel: 'low',
        },
    },
    {
        id: 'mock-waiting-2',
        subject: 'Vendor feedback on marketing',
        participants: ['vendor@owner.com'],
        classification: 'vendor_update',
        category: 'waiting',
        riskLevel: 'low',
        riskReason: null,
        nextAction: 'Wait for approval',
        nextActionOwner: 'external',
        lastMessageAt: new Date(Date.now() - 1000 * 60 * 60 * 72), // 3 days ago
        lastReplyAt: new Date(Date.now() - 1000 * 60 * 60 * 73),
        summary: 'Sent marketing proofs to vendor, waiting for sign off.',
        draftResponse: null,
        propertyId: 'prop-222',
        dealId: null,
        stage: 'listing',
        createdAt: new Date(),
        updatedAt: new Date(),
        property: {
            id: 'prop-222',
            address: '222 Second Ave',
        },
        deal: null,
    },
    {
        id: 'mock-waiting-3',
        subject: 'Builder report needed',
        participants: ['inspector@buildcheck.com'],
        classification: 'inspection',
        category: 'waiting',
        riskLevel: 'medium',
        riskReason: 'Condition deadline approaching',
        nextAction: 'Wait for report',
        nextActionOwner: 'external',
        lastMessageAt: new Date(Date.now() - 1000 * 60 * 60 * 4), // 4 hours ago
        lastReplyAt: new Date(Date.now() - 1000 * 60 * 60 * 5),
        summary: 'Inspector needs to confirm time, waiting for callback.',
        draftResponse: null,
        propertyId: 'prop-333',
        dealId: 'deal-333',
        stage: 'due_diligence',
        createdAt: new Date(),
        updatedAt: new Date(),
        property: {
            id: 'prop-333',
            address: '333 Third Blvd',
        },
        deal: {
            id: 'deal-333',
            stage: 'due_diligence',
            riskLevel: 'medium',
        },
    },
    {
        id: 'mock-waiting-4',
        subject: 'Mortgage approval',
        participants: ['buyer@newhome.com'],
        classification: 'finance',
        category: 'waiting',
        riskLevel: 'high',
        riskReason: 'Finance date tomorrow',
        nextAction: 'Wait for confirmation',
        nextActionOwner: 'external',
        lastMessageAt: new Date(Date.now() - 1000 * 60 * 60 * 20), // 20 hours ago
        lastReplyAt: new Date(Date.now() - 1000 * 60 * 60 * 21),
        summary: 'Buyer is chasing bank for final approval.',
        draftResponse: null,
        propertyId: 'prop-444',
        dealId: 'deal-444',
        stage: 'finance',
        createdAt: new Date(),
        updatedAt: new Date(),
        property: {
            id: 'prop-444',
            address: '444 Fourth Ln',
        },
        deal: {
            id: 'deal-444',
            stage: 'finance',
            riskLevel: 'high',
        },
    },
    {
        id: 'mock-waiting-5',
        subject: 'council file request',
        participants: ['council@city.gov'],
        classification: 'admin',
        category: 'waiting',
        riskLevel: 'low',
        riskReason: null,
        nextAction: 'Wait for files',
        nextActionOwner: 'external',
        lastMessageAt: new Date(Date.now() - 1000 * 60 * 60 * 96), // 4 days ago
        lastReplyAt: new Date(Date.now() - 1000 * 60 * 60 * 100),
        summary: 'Requested property files from council, standard 5 day turnaround.',
        draftResponse: null,
        propertyId: 'prop-555',
        dealId: null,
        stage: 'listing',
        createdAt: new Date(),
        updatedAt: new Date(),
        property: {
            id: 'prop-555',
            address: '555 Fifth Ct',
        },
        deal: null,
    },
];
