import { ZenaToolDefinition } from '../types.js';
import { toolRegistry } from '../registry.js';
import prisma from '../../config/database.js';

export const refreshIntelligenceTool: ZenaToolDefinition = {
    name: 'property.refresh_intelligence',
    domain: 'property',
    description: 'Trigger an AI analysis refresh for property momentum and interest.',

    inputSchema: {
        type: 'object',
        properties: {
            propertyId: { type: 'string' }
        },
        required: ['propertyId']
    },

    outputSchema: {
        type: 'object',
        properties: {
            prediction: { type: 'object' }
        }
    },

    permissions: ['properties:write'],
    requiresApproval: false,

    execute: async (params, context) => {
        const userId = context.userId;
        const { propertyId } = params;

        const property = await prisma.property.findFirst({
            where: { id: propertyId, userId }
        });

        if (!property) return { success: false, error: 'Property not found' };

        // For now, simulate an AI update by updating or creating the PropertyPrediction
        const prediction = await prisma.propertyPrediction.upsert({
            where: { propertyId },
            create: {
                propertyId,
                momentumScore: Math.floor(Math.random() * 40) + 50,
                buyerInterestLevel: ['Low', 'Medium', 'High', 'Hot'][Math.floor(Math.random() * 4)],
                reasoning: 'Generated by Zena Agent refresh.',
                confidenceScore: 0.85
            },
            update: {
                momentumScore: Math.floor(Math.random() * 40) + 50,
                buyerInterestLevel: ['Low', 'Medium', 'High', 'Hot'][Math.floor(Math.random() * 4)],
                reasoning: 'Updated by Zena Agent refresh.',
                lastAnalyzedAt: new Date()
            }
        });

        return {
            success: true,
            data: { prediction }
        };
    },

    auditLogFormat: (input, _output) => ({
        action: 'PROPERTY_INTELLIGENCE_REFRESH',
        summary: `Refreshed intelligence for property ${input.propertyId}`
    })
};

toolRegistry.register(refreshIntelligenceTool);
